apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
  namespace: project
spec:
  storageClassName: "imagesaving"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi