apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-port
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-port
  template:
    metadata:
      labels:
        app: server-port
    spec:
      volumes:
        - name: imagesave
          persistentVolumeClaim:
            claimName: image-pvc
      containers:
        - name: server-port
          image: server-port:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: BACKEND_URL
              value: "http://todo-backend-svc:8000"
          volumeMounts:
            - name: imagesave
              mountPath: /app/images