apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  storageClassName: "pongsaving"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/kube