apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: exercises
spec:
  rules:
    - host: log-output.local
      http:
        paths:
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 2345
          - path: /ping
            pathType: Prefix
            backend:
              service:
                name: pong-app-svc
                port:
                  number: 2346