apiVersion: ENC[AES256_GCM,data:wlo=,iv:TpRH7tBGtpci+2K6typKCs/P84sF3wcGj9P2KmONmQ4=,tag:/teFqCDVhsTk1qeNYWiwCg==,type:str]
kind: ENC[AES256_GCM,data:/okr+X03,iv:WZmcyXSmTVa9fzgQrlCBsDgmwvJPoHTTYqGUbifkeko=,tag:bujc+FzRNesGD2JYYWarBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oPqbSDjV0YkqPzJiaR7qwMmh,iv:oLZ4C3GaUrsiPHuBUBNCj9Q+f5NmiWiV46pyIxlVW/o=,tag:uKerWiocRryq2N80VILjlg==,type:str]
type: ENC[AES256_GCM,data:lkg9G1Kj,iv:qt74O4IIDcqaQCz3bc5+pkKFnaQe79aP3LCxcjbemas=,tag:LdKXdPuN8FcecJMbqaEXsA==,type:str]
stringData:
    BROADCAST_WEBHOOK_URL: ENC[AES256_GCM,data:gFecH5jYgOhWtM7QFmoOokY4c09pLN0jvawGDns4cTQxP/1nJSXc+hmfIFa2saj/teGLE/8hM3/Xze8e5s0mHIVkVof6xvuw9BX5qJGJ+9eM,iv:36f+crt9HGZ1xTWgJOE+5dZ3KVh65U4mU7leJN8ilqY=,tag:HuzOP2FftRL1EH4QKsHSxQ==,type:str]
    BROADCAST_MODE: ENC[AES256_GCM,data:AglVaZE=,iv:v8ehVHGrXMFL0rjFagn9Y/6Vlhst+eGw3JILfMVvOe4=,tag:xbc1J6O3f78P3R2eq1yVXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc1JIL2N0WWt1ZUg3SVdP
            eDB0bllNUlN5UHNENUxzbmxjenRwSUtQelNZClhmMTg0ek1VdEd1K29NWHVlYkM4
            Q0lBSS9YL00xV1EwbThKeTIwTHA4RVEKLS0tIENqZnZocTNWclJYWTJZRXJ1ZGhI
            VG9FSExYRGVnd3FxVktPazdVa1Y5b2sKZp5mrO6G1b38plgFdR1TnPjNvnowdoAd
            ov28RzrqpOjrcXzDNAzWZtUW6B5mmapC5Var3ubG2/9bQDrBtAMA9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age156a929qc2hg6svc3lcu5hnxs06e55a53fhvhf5znswswhtn5kyrs8mv0g7
    lastmodified: "2026-09-04T19:31:09Z"
    mac: ENC[AES256_GCM,data:bfXter6mTxle2UoVuC4Y3MBIUWhv1/xly0PeRVrRkctTBfgXSkyPw6rLWSZwWdKoCHYfur6Xpa21zk4hz7H7Al/oVW24owjMppm9UfNlCrZn9z5qrG64+U2ZrjyVqb5eiVjdsxC0BYK9Z8D/dYr4nXTJhDzyc187R0WJV6yMuak=,iv:BRcvSbEeCAkLu9jIQo2Qkbux/cOrKwZHz96pVmQQBRg=,tag:QVvQoWEQKrY3dvmYivfffQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
