apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: exercises
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:km/ag6uzxqTLO3Q=,iv:zpVTGxfmelv28qNldcfydrnahHdj7zdI9NJRgO7hBeo=,tag:xEkfwH1xZ3BSwDzjtutJXg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:LFDfoBYsTwo=,iv:XVS6I8uLTqHrrStKcn55XFXBkIBZi7D5+x5M2qB2dro=,tag:bUgRxzMV9llTa93EcZ8OvA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:MpKg+6VtKelRQEhLkP/cWJv7gXoO+c8yAA==,iv:TY3LgHQ9tCVS32gRneCoBFEORDT3+xbTVREqy7pTlfE=,tag:lyrg8Sxvi8Hlpa/xiTwqLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3clUvdFNHbFNRV2RaaktP
            N1lqVmprc0JvR3VDZ1BiakVVaTJzekNMdlNNCmxYQnZIaTVNUGtTMnB3ZHBYc2Ns
            Q3VJWHRwOFRyZnpCRXdHS3hOQjUzcHcKLS0tIDExT2prUnpIT3FqcEZDNXY4Z1M0
            RmlOTHlra21pcXlTSkxLb2hNZlliRlEKLLaW7U7T3V0UxblRU+Scv8VE7j1ipoWL
            z04qxUNvwHonwLHX/cs3nSkIdKmnh4O64yStQjv6DfOVYTzKv37aQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15teeg9x3g9tsjyfdsnaewhqgmd27sndgu426kf9dc9d9u7tgh92sslyr4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T18:39:12Z"
    mac: ENC[AES256_GCM,data:U1Ss8QyXhCCbnVA4z7TqrZgOH1V9BVoOylhxhoclTgkBGS6OwdB3f2thCQS3MO15mVC1whyo8Se1jiRayHdaF0P5tOt1htXh+w3+oS+7FOXqik8Pg5bGuJanoOqfb288NSJd4dvSR/O3XH3NnFbaQhHCNRX6H1soTQtblX+bs9M=,iv:Mb82rKqLqDvMhxKugp/1AR6XukFlEdXnzgmZ0APr9fQ=,tag:fO+muvUlf3ymYEHypnTGaQ==,type:str]
    version: 3.13.3
