apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pong-cpu-usage
  namespace: exercises
spec:
  metrics:
    - name: namespace-cpu-usage
      initialDelay: 1m
      interval: 1m
      count: 5
      failureLimit: 1
      successCondition: result < 0.8
      provider:
        prometheus:
          address: http://prom-prometheus-server.monitoring.svc.cluster.local:80
          query: |
            scalar(
              sum(
                rate(
                  container_cpu_usage_seconds_total{
                    namespace="exercises",
                    container!="POD",
                    image!=""
                  }[5m]
                )
              )
            )