apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: pong-app
          image: pong-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              name: http
          volumeMounts: 
            - name: shared-logs
              mountPath: /usr/src/app/shared